### PR TITLE
Bug 1770183: Allow operator to be upgraded automatically

### PR DESCRIPTION
**Pull request by gnufied**
Allow operator to be updated automatically across minor versions.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1770183

### CODE REVIEW

**Comment by gnufied** [comment]
More information about how this is supposed to work - https://docs.openshift.com/container-platform/4.2/operators/understanding-olm/olm-understanding-olm.html#olm-upgrades-replacing-multiple_olm-understanding-olm

**Comment by jsafrane** [comment]
/retitle Bug 1770183: Allow operator to be upgraded automatically

**Pull request merged**
