### PR TITLE
[release-4.12] OCPBUGS-13357: add multipath support for volume discovery

### PR DESCRIPTION
**Pull request by RomanBednar**
This is a manual cherry-pick of https://github.com/openshift/local-storage-operator/pull/394

/assign RomanBednar

### CODE REVIEW

**Comment by dobsonj** [comment]
@RomanBednar do you still want to merge this? (sorry it's been sitting here for quite some time)
I think you missed the patch for `getValidBlockDevices` from https://github.com/openshift/local-storage-operator/pull/394 but the rest looks fine to me.

/remove-lifecycle rotten

**Comment by duanwei33** [comment]
@Phaow Could you help check if we could pre-merge test or label it directly?

**Comment by Phaow** [comment]
@duanwei33 Sure, working on it now, but seems the cluster-bot have some issues failed to launch the pre merge build cluster several times.

**Comment by Phaow** [comment]
Pre verify passed with the prebuild cluster by clusterbot
```console
$ oc version
Client Version: 4.12.0-ec.3
Kustomize Version: v5.0.1
Server Version: 4.12.0-0.test-2023-11-07-073945-ci-ln-4sbi2b2-latest
Kubernetes Version: v1.25.14+bcb9a60
1. Install OCP cluster and local storage operator;
2. Configure multipath on 1 worker node;
3. Create localvolumediscovery CR and check the localvolumediscoveryResults contains the mpath type volumes;
$ oc get localvolumediscoveryResults -oyaml|grep -i 'mpath'
    - deviceID: /dev/disk/by-id/dm-name-mpatha
      type: mpath
4. Create localvolumeset with mpath type and check the provisioned pvs contains the mpath volumes.(Check both with CLI and Web console)
$ oc get pv/local-pv-2bbeeadc -oyaml|yq .metadata.annotations
pv.kubernetes.io/provisioned-by: local-volume-provisioner-ci-ln-4sbi2b2-72292-dncnt-worker-c-rtlht
storage.openshift.com/device-id: dm-name-mpatha
storage.openshift.com/device-name: dm-0
```

**Pull request merged**
