### PR TITLE
manifests/local-storage-operator.package.yaml: standardize channel name

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by sosiouxme** [comment]
@bertinatto @jsafrane these changes are necessary to get this operator working in OCP 4.2

**Comment by jsafrane** [comment]
@sosiouxme, please check the failed test, something needs to be updated with the new path:

```
cat: ./hack/../deploy/crd.yaml: No such file or directory
```

**Comment by sosiouxme** [comment]
@jsafrane yes, i don't understand this well enough to know what is looking at that and why. is it just a script that needs to be updated to match the changed layout?

**Comment by gnufied** [comment]
The deploy script uses symlink from manifests directory into deploy directory. This PR makes the symlink invalid. We just need to fix the symlink in `deploy/crd.yaml` to point to new location.

**Comment by sosiouxme** [comment]
ah, i see, very simple, sorry i missed that... trying again

**Comment by sosiouxme** [comment]
basic tests at least are succeeding now, can i get a lgtm/approve?

**Pull request merged**
