### PR TITLE
4.2: Bug 1781871: Fix code for finding new disks

### PR DESCRIPTION
**Pull request by gnufied**
Fix finding of localvolume disks for lvm disks.

### CODE REVIEW

**Comment by huffmanca** [comment]
I examined this to compare it to https://github.com/openshift/local-storage-operator/pull/67 (which is already merged), and it looks good to me.

**Comment by jsafrane** [comment]
Set BZ labels manually, #1781871 is a valid 4.2.z bug.

**Comment by jsafrane** [comment]
Wait, the bot is right... We need the 4.3 and 4.4 bugs tested first.
/bugzilla refresh

**Pull request merged**
