### PR TITLE
Bug 2027008: diskmaker-discovery pods don't start because of missing …

### PR DESCRIPTION
**Pull request by dobsonj**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2027008
/cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm cancel

I wonder, is the service used in multiple places, for diskmaker and discovery?

**Comment by dobsonj** [comment]
Just to be sure, I destroyed and re-created my local cluster, and confirmed that this image:
```
    image: quay.io/jdobson/local-storage-operator:bug2027008
```
can start diskmaker-discovery and diskmaker-manager pods successfully.
```
$ oc get pods -n openshift-local-storage
NAME                                                              READY   STATUS      RESTARTS   AGE
1860f09b7c7dc9312d456d8fc0ba49ff697d5324dc37570298abae--1-65znv   0/1     Completed   0          4m32s
diskmaker-discovery-cjrfz                                         2/2     Running     0          2m6s
diskmaker-manager-sth9v                                           2/2     Running     0          45s
local-storage-operator-656858dfb9-c4qm9                           1/1     Running     0          4m9s
localstorage-operator-manifests-tv5vp                             1/1     Running     0          4m55s
```
So the fix for this PR works, but the issue I see is that CI is pulling and testing the wrong image.
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_local-storage-operator/301/pull-ci-openshift-local-storage-operator-master-e2e-operator/1468896840685457408/artifacts/e2e-operator/gather-extra/artifacts/events.json
```
"message": "Successfully pulled image \"quay.io/openshift/origin-local-storage-operator\" in 4.64993059s",
```
That's the build from master, not from the open PR.

**Comment by dobsonj** [comment]
> the issue I see is that CI is pulling and testing the wrong image.
I filed https://bugzilla.redhat.com/show_bug.cgi?id=2030776 for this issue.

**Pull request merged**
