### PR TITLE
Add label for ARM to display local storage operator

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
in the OperatorHub.

Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

### CODE REVIEW

**Comment by dobsonj** [comment]
@SaravanaStorageNetwork Which release is this targeting?
If 4.10, then we would need a valid bugzilla, since we're past feature freeze and can only merge bug fixes right now.
If 4.11, then we would need to wait to merge until the dev branch opens on Jan 28 (that's only a couple of weeks away though).

**Comment by yselkowitz** [comment]
This operator first needs to be (at least preliminary) validated before the label is applied (which will cause it to be displayed in OperatorHub).
/hold

**Comment by SaravanaStorageNetwork** [comment]
@yselkowitz 

I could do a initial validation of local storage operator in OCP-4-10 ARM cluster. Looks fine. 

```
oc -n openshift-local-storage get all 
NAME                                          READY   STATUS    RESTARTS   AGE
pod/local-storage-operator-786d7bf6cf-fp55w   1/1     Running   0          113m

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/local-storage-operator   1/1     1            1           113m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/local-storage-operator-786d7bf6cf   1         1         1       113m
```

**Comment by yselkowitz** [comment]
can you create PVs?  can you get PVCs to be resolved with LSO based PVs?

**Comment by SaravanaStorageNetwork** [comment]
@yselkowitz  

I could create both file and block based PVCs. 
Verified this in version: 4.10.0-0.nightly-arm64-2022-01-29-162645

**Comment by SaravanaStorageNetwork** [comment]
@dobsonj  The target is for 4.11 only. LMK if anything required from my end.

**Comment by SaravanaStorageNetwork** [comment]
> /lgtm /assign @dobsonj

To remove the flag:
/unhold

**Pull request merged**
