### PR TITLE
Migrates the project to use Go modules

### PR DESCRIPTION
**Pull request by ashishranjan738**
This commit migrates the local-storage-operator project to use go modules for dependency management.

Signed-off-by: Ashish Ranjan <ashishranjan738@gmail.com>

### CODE REVIEW

**Comment by jsafrane** [comment]
You must bump also golang version in all Dockerfiles.

**Comment by ashishranjan738** [comment]
> You must bump also golang version in all Dockerfiles.

yeah done

**Comment by ashishranjan738** [comment]
closing this PR since it the PR #101 contains this commit

**Pull request closed without merging**
