### PR TITLE
Bug 1954687: Reenabled commented out e2e tests for LocalVolumeDiscovery and LocalVolumeSet

### PR DESCRIPTION
**Pull request by priyanka19-98**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1954687

Signed off by: Priyanka Jiandani <pjiandan@redhat.com>

### CODE REVIEW

**Comment by rohantmp** [comment]
/retitle Reenabled commented out e2e tests for LocalVolumeDiscovery and LocalVolumeSet

**Comment by rohantmp** [comment]
I accidentally commented these out while fixing review comments for the provisioner-as-a-lib PR.

**Comment by gnufied** [comment]
We can't merge this without a bug.

/lgtm

**Pull request merged**
