### PR TITLE
Bug 2001765: deleter: Don't call reconciler with PVs

### PR DESCRIPTION
**Pull request by jsafrane**
`For()` will call `DeleteReconciler` with PVs, whose namespace is empty. This results in errors:

```
  ERROR	deleter	could not get provisioner configmap	{"Request.Namespace": "", "Request.Name": "local-pv-26ba56f", "error": "ConfigMap \"local-provisioner\" not found"}
```

PVs are already processed by `Watches()` and requests will be reconciled with the correct LSO namespace. Use the deleter ConfigMap in `For()`.

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
A reconciler *must* have some `For()`.

**Comment by sp98** [comment]
LGTM

**Pull request merged**
